import type { Vector3 } from 'three';
import type { EntityId } from '../core.js';
import type { Team, ShipHull } from '../gameplay.js';
import type { DoctrineState } from './doctrine.js';
import type { AIMetrics } from './metrics.js';

/**
 * High-level intent driving an AI ship's behavior.
 */
export type AIIntent =
  | 'Attack'
  | 'Kite'
  | 'Escort'
  | 'Intercept'
  | 'Flee'
  | 'Regroup'
  | 'Reposition';

/**
 * Output command generated by the AI system for a ship.
 */
export interface AICommand {
  /** Desired heading vector. */
  heading: Vector3;
  /** Throttle level (0..1). */
  thrust: number;
  /** Optional lateral strafe input in range [-1, 1]. */
  strafe?: number;
  /** Whether to fire primary weapons. */
  firePrimary: boolean;
  /** Orbit direction/factor. */
  orbit?: number;
  /** Entity ID of the current target. */
  targetId?: EntityId;
  /** Time to live for this command in seconds. */
  ttl: number;
}

/**
 * Individual personality traits for an AI agent.
 */
export interface AITraits {
  /** Tendency to close distance and engage. */
  aggression: number;
  /** Tendency to wait for better shots/positioning. */
  patience: number;
  /** Tendency to perform evasive maneuvers. */
  dodge: number;
}

/**
 * Component representing the internal state of an AI agent.
 */
export interface AIState {
  /** ID of the behavior profile being used. */
  profileId: string;
  /** Current high-level intent. */
  intent: AIIntent;
  /** Game tick when the AI will next update its decision. */
  nextThinkAt: number;
  /** Cooldown timers for specific actions. */
  cooldowns: {
    dodgeAt: number;
    burstAt: number;
  };
  /** Level of Detail for AI processing (0=high, 1=med, 2=low). */
  lod: 0 | 1 | 2;
  /** Seed used for deterministic random behavior. */
  traitSeed: number;
  /** Personality traits. */
  traits: AITraits;
  /** Currently selected target ID. */
  targetId?: EntityId;
  /** Score of the current target/action from the last evaluation. */
  lastScore?: number;
  /** Current active command driving the ship. */
  command: AICommand;
  /** Time until which the current intent is "sticky" and resists change. */
  stickinessUntil: number;
  /** Heading vector stored for sticky maneuvers. */
  stickinessHeading: Vector3;
  /** Target ID stored for sticky targeting. */
  stickinessTargetId?: EntityId;
  /** Desired engagement range [min, max]. */
  desiredRange?: readonly [number, number];
}

/**
 * Static configuration defining a class or style of AI behavior.
 */
export interface BehaviorProfile {
  /** Preferred combat range interval [min, max]. */
  desiredRange: readonly [number, number];
  /** Orbit distance preference. */
  orbit: number;
  /** Base aggression level. */
  aggression: number;
  /** Base patience level. */
  patience: number;
  /** Frequency of dodge maneuvers. */
  dodgeFreq: number;
  /** Bias multipliers against specific ship hulls. */
  classBias: Partial<Record<ShipHull, number>>;
  /** Combat style classification. */
  style: 'brawler' | 'kiter' | 'artillery' | 'escort';
  /** Thresholds for state transitions. */
  gates?: {
    ammoMin?: number;
    hpRetreatPct?: number;
  };
  /** Factor for vertical maneuverability usage. */
  verticalManeuver: number;
  /** Preferred vertical position relative to target. */
  elevationPreference?: 'above' | 'below' | 'follow';
  /** Preferred radial band in the battlefield. */
  bandPreference?: 'outer' | 'mid' | 'inner';
  /** Bias added to engagement scores. */
  engagementBias?: number;
}

/**
 * Strategic posture of a team.
 */
export type TeamPosture = 'aggressive' | 'hold' | 'retreat';

/**
 * Shared data structure for AI team coordination and situational awareness.
 */
export interface AIBlackboard {
  /** Current game tick index. */
  tickIndex: number;
  /** Current posture for each team. */
  teamPosture: Record<Team, TeamPosture>;
  /** Centroid position of each team's fleet. */
  allyCentroid: Record<Team, Vector3>;
  /** Map of ship ID to its nearest enemy ID. */
  nearestEnemy: Map<EntityId, EntityId>;
  /** Map of VIP ship ID to its primary threat ID. */
  threatToVip: Map<EntityId, EntityId>;
  /** Pool of temporary vectors for calculation. */
  tmpVectors: Vector3[];
  /** Ratio of team strength relative to the opponent. */
  strengthRatio: Record<Team, number>;
  /** List of prioritized targets for each team. */
  teamPriority: Record<Team, PrioritisedTarget[]>;
  /** Map of target ID to its priority index. */
  priorityIndex: Record<Team, Map<EntityId, number>>;
  /** Map tracking how many allies are focusing each enemy. */
  focusFire: Record<Team, Map<EntityId, number>>;
  /** Visibility status of enemies for each team. */
  visibleEnemies?: Record<Team, Map<EntityId, SensorVisibility>>;
  /** Ship counts per team. */
  teamCounts?: Record<Team, number>;
  /** Vertical dispersion tracking for validation (optional for backward compatibility). */
  verticalDispersion?: {
    headingYSamples: number[];
    positionYSamples: number[];
    lastUpdateTick: number;
  };
}

/**
 * Assignments for team-level coordination.
 */
export interface AITeamAssignments {
  /** Map of escort ship ID to assignment details. */
  escorts: Map<EntityId, EscortAssignment>;
}

/**
 * Details of an escort mission.
 */
export interface EscortAssignment {
  /** ID of the ship to protect. */
  vipId: EntityId;
  /** Formation offset from the VIP. */
  offset: Vector3;
  /** ID of the threat currently engaging the VIP. */
  threatId?: EntityId;
}

/**
 * Snapshot of AI intents at a specific time for metrics/debugging.
 */
export interface AIIntentSnapshot {
  /** Game tick of the snapshot. */
  tick: number;
  /** Game time of the snapshot. */
  time: number;
  /** Counts of ships in each intent state. */
  counts: Partial<Record<AIIntent, number>>;
  /** Total number of ships tracked. */
  total: number;
}

/**
 * Evaluation of a potential target's priority.
 */
export interface PrioritisedTarget {
  /** ID of the target entity. */
  id: EntityId;
  /** Calculated threat score. */
  threat: number;
  /** Squared distance to the target. */
  distanceSq: number;
  /** Number of allies currently focusing this target. */
  focusLoad: number;
}

/**
 * Reasons why an AI might interrupt its current intent.
 */
export type AIInterruptReason = 'hp-drop' | 'target-lost' | 'vip-threat' | 'manual';

/**
 * Record of an interrupt event.
 */
export interface IntentInterruptEvent {
  /** ID of the ship being interrupted. */
  shipId: EntityId;
  /** Reason for the interrupt. */
  reason: AIInterruptReason;
  /** Game tick when the interrupt occurred. */
  tick: number;
  /** Source ID associated with the interrupt (e.g., attacker). */
  sourceId?: EntityId;
}

/**
 * State tracking for the interrupt system.
 */
export interface AIInterruptState {
  /** Map of cooldown keys to expiration ticks. */
  cooldownTick: Map<string, number>;
  /** Map of accumulated damage per ship this tick. */
  damageThisTick: Map<EntityId, number>;
  /** Last tick where damage was processed. */
  lastDamageTick: number;
  /** Map of VIPs to their current threats. */
  vipThreatAssignments: Map<EntityId, EntityId>;
}

/**
 * Histogram data for shot statistics.
 */
export interface AIShotHistogram {
  /** Bucket boundaries. */
  buckets: readonly number[];
  /** Counts per bucket. */
  counts: number[];
  /** Total number of shots recorded. */
  total: number;
}

/**
 * Statistics for range-keeping behavior.
 */
export interface AIInBandStats {
  /** Total number of samples. */
  samples: number;
  /** Number of samples within desired range. */
  satisfied: number;
}

/**
 * State of a sensor contact.
 */
export interface SensorVisibility {
  /** Signal strength (0..1). */
  strength: number;
  /** Tick index when the contact was last seen. */
  lastSeenTick: number;
  /** ID of the ship detecting this contact. */
  sourceId: EntityId;
  /** Whether the contact is currently occluded. */
  occluded: boolean;
  /** Distance to the contact. */
  distance: number;
}

/**
 * State of the sensor system.
 */
export interface SensorState {
  /** Last tick the sensors were updated. */
  lastUpdateTick: number;
  /** Visibility map per team. */
  visibilityByTeam: Record<Team, Map<EntityId, SensorVisibility>>;
  /** Rate at which signal strength decays. */
  decayRate: number;
  /** Minimum signal strength for detection. */
  threshold: number;
  /** Tick duration before a stale contact is removed. */
  staleDecay: number;
}

/**
 * Top-level state for the AI manager.
 */
export interface AIManagerState {
  /** Global AI enable switch. */
  enabled: boolean;
  /** Number of ticks between AI updates for a given ship. */
  tickInterval: number;
  /** Maximum number of AI updates per tick (budget). */
  maxPerTick: number;
  /** Time accumulator for AI processing. */
  accumulator: number;
  /** Current tick index. */
  tickIndex: number;
  /** Cursor for round-robin scheduling. */
  cursor: number;
  /** Number of scheduling slices. */
  slices: number;
  /** Team-level assignments. */
  assignments: AITeamAssignments;
  /** Collected metrics. */
  metrics: AIMetrics;
  /** Doctrine system state. */
  doctrine?: DoctrineState;
  /** List of pending interrupts. */
  interrupts?: IntentInterruptEvent[];
  /** Internal state of the interrupt system. */
  interruptState?: AIInterruptState;
}
