import type { Vector3 } from 'three';
import type { EntityId } from '../core.js';
import type { ShipHull } from '../gameplay.js';
import type { DoctrineState } from './doctrine.js';
import type { AIMetrics } from './metrics.js';
import type { AITeamAssignments } from './blackboard.js';
import type { AIInterruptState, IntentInterruptEvent } from './interrupts.js';

// Re-export the focused AI type modules so existing `./ai/state.js` imports
// keep working unchanged.
export type {
  TeamPosture,
  PrioritisedTarget,
  AIBlackboard,
  AITeamAssignments,
  EscortAssignment,
} from './blackboard.js';
export type { SensorVisibility, SensorState } from './sensors.js';
export type { AIInterruptReason, IntentInterruptEvent, AIInterruptState } from './interrupts.js';
export type { AIIntentSnapshot, AIShotHistogram, AIInBandStats } from './metrics-snapshots.js';

/**
 * High-level intent driving an AI ship's behavior.
 */
export type AIIntent =
  | 'Attack'
  | 'Kite'
  | 'Escort'
  | 'Intercept'
  | 'Flee'
  | 'Regroup'
  | 'Reposition';

/**
 * Output command generated by the AI system for a ship.
 */
export interface AICommand {
  /** Desired heading vector. */
  heading: Vector3;
  /** Throttle level (0..1). */
  thrust: number;
  /** Optional lateral strafe input in range [-1, 1]. */
  strafe?: number;
  /** Whether to fire primary weapons. */
  firePrimary: boolean;
  /** Orbit direction/factor. */
  orbit?: number;
  /** Entity ID of the current target. */
  targetId?: EntityId;
  /** Time to live for this command in seconds. */
  ttl: number;
}

/**
 * Individual personality traits for an AI agent.
 */
export interface AITraits {
  /** Tendency to close distance and engage. */
  aggression: number;
  /** Tendency to wait for better shots/positioning. */
  patience: number;
  /** Tendency to perform evasive maneuvers. */
  dodge: number;
}

/**
 * Component representing the internal state of an AI agent.
 */
export interface AIState {
  /** ID of the behavior profile being used. */
  profileId: string;
  /** Current high-level intent. */
  intent: AIIntent;
  /** Game tick when the AI will next update its decision. */
  nextThinkAt: number;
  /** Cooldown timers for specific actions. */
  cooldowns: {
    dodgeAt: number;
    burstAt: number;
  };
  /** Level of Detail for AI processing (0=high, 1=med, 2=low). */
  lod: 0 | 1 | 2;
  /** Seed used for deterministic random behavior. */
  traitSeed: number;
  /** Personality traits. */
  traits: AITraits;
  /** Currently selected target ID. */
  targetId?: EntityId;
  /** Score of the current target/action from the last evaluation. */
  lastScore?: number;
  /** Current active command driving the ship. */
  command: AICommand;
  /** Time until which the current intent is "sticky" and resists change. */
  stickinessUntil: number;
  /** Heading vector stored for sticky maneuvers. */
  stickinessHeading: Vector3;
  /** Target ID stored for sticky targeting. */
  stickinessTargetId?: EntityId;
  /** Desired engagement range [min, max]. */
  desiredRange?: readonly [number, number];
}

/**
 * Static configuration defining a class or style of AI behavior.
 */
export interface BehaviorProfile {
  /** Preferred combat range interval [min, max]. */
  desiredRange: readonly [number, number];
  /** Orbit distance preference. */
  orbit: number;
  /** Base aggression level. */
  aggression: number;
  /** Base patience level. */
  patience: number;
  /** Frequency of dodge maneuvers. */
  dodgeFreq: number;
  /** Bias multipliers against specific ship hulls. */
  classBias: Partial<Record<ShipHull, number>>;
  /** Combat style classification. */
  style: 'brawler' | 'kiter' | 'artillery' | 'escort';
  /** Thresholds for state transitions. */
  gates?: {
    ammoMin?: number;
    hpRetreatPct?: number;
  };
  /** Factor for vertical maneuverability usage. */
  verticalManeuver: number;
  /** Preferred vertical position relative to target. */
  elevationPreference?: 'above' | 'below' | 'follow';
  /** Preferred radial band in the battlefield. */
  bandPreference?: 'outer' | 'mid' | 'inner';
  /** Bias added to engagement scores. */
  engagementBias?: number;
}

/**
 * Top-level state for the AI manager.
 */
export interface AIManagerState {
  /** Global AI enable switch. */
  enabled: boolean;
  /** Number of ticks between AI updates for a given ship. */
  tickInterval: number;
  /** Maximum number of AI updates per tick (budget). */
  maxPerTick: number;
  /** Time accumulator for AI processing. */
  accumulator: number;
  /** Current tick index. */
  tickIndex: number;
  /** Cursor for round-robin scheduling. */
  cursor: number;
  /** Number of scheduling slices. */
  slices: number;
  /** Team-level assignments. */
  assignments: AITeamAssignments;
  /** Collected metrics. */
  metrics: AIMetrics;
  /** Doctrine system state. */
  doctrine?: DoctrineState;
  /** List of pending interrupts. */
  interrupts?: IntentInterruptEvent[];
  /** Internal state of the interrupt system. */
  interruptState?: AIInterruptState;
}
