export type {
  AIIntent,
  AICommand,
  AITraits,
  AIState,
  BehaviorProfile,
  TeamPosture,
  AIBlackboard,
  AITeamAssignments,
  EscortAssignment,
  AIIntentSnapshot,
  PrioritisedTarget,
  AIInterruptReason,
  IntentInterruptEvent,
  AIInterruptState,
  AIShotHistogram,
  AIInBandStats,
  SensorVisibility,
  SensorState,
  AIManagerState,
} from './ai/state.js';

export type {
  DoctrineCardId,
  DoctrineCard,
  DoctrineState,
  DoctrineProfileModifiers,
  DoctrineThreatModifiers,
  DoctrineSquadDirectives,
  DoctrineSensorModifiers,
  DoctrineRuntimeState,
} from './ai/doctrine.js';

export type {
  AIInBandSummary,
  AIInBandSummaryByHull,
  AIFirstShotSummary,
  AIOpeningAggressionSummary,
  AIVerticalSummary,
  AIDecisionLatencySummary,
  AIFocusFireSummary,
  AIHeadingAmplitudeSummary,
  AITieSummary,
  AIKpiSummary,
  AIMetrics,
} from './ai/metrics.js';
