name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: lts/*
          cache: true
      - name: Install deps
        run: vp install --frozen-lockfile
      - name: Install Playwright Browsers
        run: vp exec playwright install --with-deps
      - name: Run Playwright tests
        run: vp exec playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
